### ISSUE TITLE
Features and general planning

### ISSUE THREAD

**Issue by incompetentfox** [maaarghk/SteamieBot#1] opened 2015-12-10 21:39 UTC
Features
---
- [x] Function to get Weather
- [x] Function to get Gig listings
- [ ] Today in history
- [ ] Scottish word of the day
- [x] tune of the day
- [x] Travel updates?
- [x] function to compile everything into a post and submit
- [x] oauth
- [x] Flair
- [x] Auto sticky

Planning
---
* Need decent feeds for word of the day and today in history
* Suggestion: Function whereby people can submit a tune of the day via PM to the bot.
* MO: Have bot run as a CRON job once a day maybe?

**Comment by maaarghk** [comment] 2015-12-10 21:49
Tidied up the post a bit, hope you don't mind.

Someone else offered to do the hosting as they currently host another bot, they can provide input on whether or not it would be a cron job or a service or whatever. I think a cron job is probably a good idea, since its a daily thing rather than an automoderator style thing.

Quite like the tune of the day submission idea altho I can imagine some, eh, interesting suggestions coming through :P Part of the fun tho, right?

**Comment by incompetentfox** [comment] 2015-12-10 21:58
Definitely- Should probably mention that I have literally no formal training and I'm more or less making this up as I go along which will doubtlessly become painfully apparent once I do the first commit. 

Basically, if you see me do something daft, please let me know so I can avoid repeating the mistake :)

**Comment by maaarghk** [comment] 2015-12-10 22:00
lol, no bother. In fairness I'm too busy to be doing anything major at the minute cos I've got some freelance work on the go but will happily do some tidying up.

**Comment by maaarghk** [comment] 2015-12-11 09:32
@timlardner  - what do you think about how it should run, cron sound good? p.s. I will pm you the login details for the account I made.

**Comment by timlardner** [comment] 2015-12-11 09:50
Cron sounds good to me - it's a simple enough service and we want to post it at the same time every day.

I recommend forecast.io for weather. It's got a nice API and I've used it before with python.

**Comment by timlardner** [comment] 2015-12-11 10:24
@incompetentfox Shall we collaborate on this? Quite happy to write some functions and contribute to the code.

**Comment by maaarghk** [comment] 2015-12-11 10:29
@timlardner I think @incompetentfox has already started but hasn't committed anything yet, seems i managed to accidentally edit that detail out the OP.

**Comment by incompetentfox** [comment] 2015-12-11 10:30
@timlardner sounds good to me! I've knocked up a quick and dirty weather function using pyowm, but if there's a better alternative I'm happy to go with that instead!

Library-wise I've been using six.moves.urllib to fetch pages then parsing with BeautifulSoup. Does that suit everyone?

**Comment by maaarghk** [comment] 2015-12-11 10:32
I think that will be good for getting things like travel updates from ScotRail but sounds like it won't be necessary for the weather if forecast.io has a json api?

**Comment by incompetentfox** [comment] 2015-12-11 10:35
I'm using OpenWeatherMaps' json api, sorry, should've made that clear!

**Comment by timlardner** [comment] 2015-12-11 11:06
Sounds good to me. I think forecast.io is a bit more accurate than owm, but it's down to personal preference. You could probably just hard-code it to say 'rain' every day and you'd be right 95% of the time.

For tune of the day, shall we accept PM's after the time of the previous day's post, then choose one randomly?

**Comment by maaarghk** [comment] 2015-12-11 11:09
If it only runs once a day then all we really need to do is read in all the PMs before the post is made and pick one randomly at that point, right?

**Comment by timlardner** [comment] 2015-12-11 11:14
Yup. Shall I start coding it up?

**Comment by maaarghk** [comment] 2015-12-11 11:18
go for it!

**Comment by incompetentfox** [comment] 2015-12-11 11:40
A suggestion for song of the day- could we have it cache suggestions on days with multiple suggestions for days where no song has been submitted?

**Comment by timlardner** [comment] 2015-12-11 11:44
If no songs have been submitted, there's also the option of choosing a song by a band that's playing that night?

**Comment by incompetentfox** [comment] 2015-12-11 11:46
Great idea! I'll work out a way for my gig function to optionally return just a band name if you like.

**Comment by timlardner** [comment] 2015-12-11 11:47
I'll get the 'PM a song' bit working first, then we can expand it to cater for cases where there are no songs :)

**Comment by incompetentfox** [comment] 2015-12-12 14:38
I'm pretty much done with the train updates. Do we want to bother with roads? The thread as it stands doesn't tend usually include them, but that's probably just my own laziness talking! Will attempt a commit of the three completed functions so far...

**Comment by timlardner** [comment] 2015-12-12 16:56
Looks good. Reddit are discontinuing username/password login for their API in the near future, so we also need to ensure we're using OAuth.

**Comment by timlardner** [comment] 2015-12-13 14:37
Updated with the 'tune of the day' function. To prevent folk trying to game the system, it only allows one suggestion per user and ensures that users have accounts older than 30 days. Easy enough to change though, if we decide it's not necessary.

I think we're nearly ready to get the bot posting the daily threads. Just need to get OAuth working and I'll write a cron script to run it on my server.

Once it's ready, I reckon we should sticky a post on the subreddit explaining that we've got a bot and how to send it song suggestions etc.

**Comment by maaarghk** [comment] 2015-12-13 14:41
nice. I'm just about to commit the oauth stuff.

**Comment by maaarghk** [comment] 2015-12-13 15:27
@timlardner @incompetentfox  - oauth done. sent you PMs with oauth.ini on reddit

**Comment by timlardner** [comment] 2015-12-13 15:42
Got it. Managed to post from my server, but got a prompt for a captcha. Have you seen this?

**Comment by incompetentfox** [comment] 2015-12-13 15:45
Argh, that might have something to do with the bot needing more karma... not much of a choice beyond grinding it. Make a post in /r/freekarma, maybe? Also, @timlardner, if the default return on the tune function doesn't encourage people to submit their own tunes, I don't know what will...

**Comment by maaarghk** [comment] 2015-12-13 15:47
I'll post in freekarma just now then.

I just pushed link flair, along with config file functionality so we can run test features on the test sub.

**Comment by incompetentfox** [comment] 2015-12-13 15:48
Sweet. I had considered maybe having a config file with 'special day' lookup, i.e. for Christmas/St Andrew's day/Donald Trump's birthday messages. What do you guys think?

**Comment by timlardner** [comment] 2015-12-13 15:53
Heh yeah that'd be cool. We can also make manual changes to the post as and when required. 

What do you think about sticky-ing the daily discussion posts? I can chat to the mods about allowing it.

**Comment by maaarghk** [comment] 2015-12-13 15:57
re: stickying, up to them I guess, I've no strong preference either way.

special day lookup is a good idea, don't know if a config file is the best way to implement it but then again i guess it doesnt really matter, we're not going to be winning any computer science awards for this :)

**Comment by incompetentfox** [comment] 2015-12-13 16:06
I'd thought a separate file (maybe a wiki page or something like that) so that it can be edited and added to without having to mess around inside the bot.

Comp sci wise, frankly, I don't know any better- as I mentioned before, the only programming training I have is this: http://www.asciimation.co.nz/gallery2/main.php?g2_view=core.DownloadItem&g2_itemId=5529&g2_GALLERYSID=TMP_SESSION_ID_DI_NOISSES_PMT . If it runs without crashing I'll be ecstatic! 

I'm with @timlardner about the stickying, leave it up to the mods. It's rare that enough happens of a day to knock it off the front page, and it's often the top thread anyway.

**Comment by timlardner** [comment] 2015-12-13 17:49
Aye, that's a fair point. We do it on the bodybuilding subreddit, but I guess there's a lot more posts there that will bury the daily discussion. 

I like @incompetentfox's idea of a config file. It can be hosted here and the bot can check for updates.

**Comment by timlardner** [comment] 2015-12-13 22:00
I've added the script to the cron job on my server. It should post in the test subreddit at 5am each morning.

**Comment by timlardner** [comment] 2015-12-14 08:40
@maaarghk, I just saw your commit. The post failed this morning because random was missing and I spent the last 5 minutes wondering why it didn't work since it was imported. Let's try again tomorrow!

**Comment by maaarghk** [comment] 2015-12-14 17:28
first day largely a success then? 

i was thinking we should consider a few things 
* using travel updates titles only - could get messy when there are a lot (See test sub)
* updating the post with travel updates through the day  - would need to introduce switches on the command line but not a huge deal is it?

**Comment by timlardner** [comment] 2015-12-14 18:21
Nah should be easy enough to do. Just have a --update option that will find the latest post and edit the necessary sections. We could run it on an hourly basis during the day.

**Comment by maaarghk** [comment] 2015-12-15 09:31
Problems running it this am?

**Comment by timlardner** [comment] 2015-12-15 09:34
Yeah, error copied below. I think reddit had some problems this morning though, see the sticky at the top of /r/askreddit.

Traceback (most recent call last):
  File "steamiebot.py", line 227, in <module>
    submission = r.submit(subreddit,post[0],text=post[1])
  File "<decorator-gen-145>", line 2, in submit
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 268, in wrap
    return function(*args, **kwargs)
  File "<decorator-gen-144>", line 2, in submit
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 174, in require_captcha
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 2616, in submit
    retry_on_error=False)
  File "<decorator-gen-8>", line 2, in request_json
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 113, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 612, in request_json
    retry_on_error=retry_on_error)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 445, in _request
    _raise_response_exceptions(response)
  File "/usr/local/lib/python2.7/dist-packages/praw/internal.py", line 212, in _raise_response_exceptions
    raise HTTPException(_raw=exc.response)
praw.errors.HTTPException: HTTP error

**Comment by maaarghk** [comment] 2016-01-18 08:23
bot hasn't posted last few times, what have the stack traces looked like / is there a problem hosting it? i can run it on my server if you like.

**Comment by timlardner** [comment] 2016-01-18 08:59
The cron job is running ok, it's returning this message:

rom redditbot@lardner.io Mon Jan 18 08:01:28 2016
Return-path: <redditbot@lardner.io>
Envelope-to: redditbot@lardner.io
Delivery-date: Mon, 18 Jan 2016 08:01:28 +0100
From: root@lardner.io (Cron Daemon)
To: redditbot@lardner.io
Subject: Cron <redditbot@lardner> cd /home/redditbot/SteamieBot; python run_steamie.py
Content-Type: text/plain; charset=UTF-8
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/home/redditbot>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=redditbot>
Date: Mon, 18 Jan 2016 08:01:28 +0100
Status: R

Traceback (most recent call last):
  File "/home/redditbot/SteamieBot/steamiebot.py", line 246, in tryPost
    postSteamie(configFile)
  File "/home/redditbot/SteamieBot/steamiebot.py", line 234, in postSteamie
    print post[1]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xec' in position 1895: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/redditbot/SteamieBot/steamiebot.py", line 246, in tryPost
    postSteamie(configFile)
  File "/home/redditbot/SteamieBot/steamiebot.py", line 234, in postSteamie
    print post[1]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xec' in position 1895: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/redditbot/SteamieBot/steamiebot.py", line 246, in tryPost                                                                         
    postSteamie(configFile)
  File "/home/redditbot/SteamieBot/steamiebot.py", line 234, in postSteamie
    print post[1]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xec' in position 1895: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/redditbot/SteamieBot/steamiebot.py", line 246, in tryPost
    postSteamie(configFile)
  File "/home/redditbot/SteamieBot/steamiebot.py", line 234, in postSteamie
    print post[1]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xec' in position 2657: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/redditbot/SteamieBot/steamiebot.py", line 246, in tryPost
    postSteamie(configFile)
  File "/home/redditbot/SteamieBot/steamiebot.py", line 234, in postSteamie
    print post[1]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xec' in position 3021: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/redditbot/SteamieBot/steamiebot.py", line 246, in tryPost
    postSteamie(configFile)
  File "/home/redditbot/SteamieBot/steamiebot.py", line 234, in postSteamie
    print post[1]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xec' in position 3024: ordinal not in range(128)
Attempting to post 'The Steamie'
From: 88ytre
Subject: SongRequest

https://www.youtube.com/watch?v=SO-Mk-Ysqbs
From: 88ytre                                                                                                                                    
Subject: SongRequest

https://www.youtube.com/watch?v=KnIgXtE4K5U
From: cosmicprincescthulhu
Subject: SongRequest

https://www.youtube.com/watc...
From: Ghost_Hands83
Subject: SongRequest

https://youtu.be/LZyqaM1hgCQ
From: Forever__Young
Subject: SongRequest

A Good Night's Sleep and a Cab Far...
From: cosmicprincescthulhu
Subject: SongRequest

https://www.youtube.com/watc...
The Steamie - Monday 18 January 2016


Failed to make daily post. Waiting 15 minutes to retry. Error: 
Attempting to post 'The Steamie'
From: 88ytre
Subject: SongRequest

https://www.youtube.com/watch?v=SO-Mk-Ysqbs                                                                                                     
From: 88ytre
Subject: SongRequest

https://www.youtube.com/watch?v=KnIgXtE4K5U
From: cosmicprincescthulhu
Subject: SongRequest

https://www.youtube.com/watc...
From: Ghost_Hands83
Subject: SongRequest

https://youtu.be/LZyqaM1hgCQ
From: Forever__Young
Subject: SongRequest

A Good Night's Sleep and a Cab Far...
From: cosmicprincescthulhu
Subject: SongRequest

https://www.youtube.com/watc...
The Steamie - Monday 18 January 2016


Failed to make daily post. Waiting 15 minutes to retry. Error: 
Attempting to post 'The Steamie'
From: 88ytre
Subject: SongRequest
                                                                                                                                                
https://www.youtube.com/watch?v=SO-Mk-Ysqbs
From: 88ytre
Subject: SongRequest

https://www.youtube.com/watch?v=KnIgXtE4K5U
From: cosmicprincescthulhu
Subject: SongRequest

https://www.youtube.com/watc...
From: Ghost_Hands83
Subject: SongRequest

https://youtu.be/LZyqaM1hgCQ
From: Forever__Young
Subject: SongRequest

A Good Night's Sleep and a Cab Far...
From: cosmicprincescthulhu
Subject: SongRequest

https://www.youtube.com/watc...
The Steamie - Monday 18 January 2016


Failed to make daily post. Waiting 15 minutes to retry. Error: 
Attempting to post 'The Steamie'
From: 88ytre
Subject: SongRequest                                                                                                                            

https://www.youtube.com/watch?v=SO-Mk-Ysqbs
From: 88ytre
Subject: SongRequest

https://www.youtube.com/watch?v=KnIgXtE4K5U
From: cosmicprincescthulhu
Subject: SongRequest

https://www.youtube.com/watc...
From: Ghost_Hands83
Subject: SongRequest

https://youtu.be/LZyqaM1hgCQ
From: Forever__Young
Subject: SongRequest

A Good Night's Sleep and a Cab Far...
From: cosmicprincescthulhu
Subject: SongRequest

https://www.youtube.com/watc...
The Steamie - Monday 18 January 2016


Failed to make daily post. Waiting 15 minutes to retry. Error: 
Attempting to post 'The Steamie'
From: 88ytre                                                                                                                                    
Subject: SongRequest

https://www.youtube.com/watch?v=SO-Mk-Ysqbs
From: 88ytre
Subject: SongRequest

https://www.youtube.com/watch?v=KnIgXtE4K5U
From: cosmicprincescthulhu
Subject: SongRequest

https://www.youtube.com/watc...
From: Ghost_Hands83
Subject: SongRequest

https://youtu.be/LZyqaM1hgCQ
From: Forever__Young
Subject: SongRequest

A Good Night's Sleep and a Cab Far...
From: cosmicprincescthulhu
Subject: SongRequest

https://www.youtube.com/watc...
The Steamie - Monday 18 January 2016


Failed to make daily post. Waiting 15 minutes to retry. Error: 
Attempting to post 'The Steamie'                                                                                                                
From: 88ytre
Subject: SongRequest

https://www.youtube.com/watch?v=SO-Mk-Ysqbs
From: 88ytre
Subject: SongRequest

https://www.youtube.com/watch?v=KnIgXtE4K5U
From: cosmicprincescthulhu
Subject: SongRequest

https://www.youtube.com/watc...
From: Ghost_Hands83
Subject: SongRequest

https://youtu.be/LZyqaM1hgCQ
From: Forever__Young
Subject: SongRequest

A Good Night's Sleep and a Cab Far...
From: cosmicprincescthulhu
Subject: SongRequest

https://www.youtube.com/watc...
The Steamie - Monday 18 January 2016


Failed to make daily post. Waiting 15 minutes to retry. Error:                                                                                  
Attempting to post 'The Steamie'
From: 88ytre
Subject: SongRequest

https://www.youtube.com/watch?v=SO-Mk-Ysqbs
From: 88ytre
Subject: SongRequest

https://www.youtube.com/watch?v=KnIgXtE4K5U
From: cosmicprincescthulhu
Subject: SongRequest

https://www.youtube.com/watc...
From: Ghost_Hands83
Subject: SongRequest

https://youtu.be/LZyqaM1hgCQ
From: Forever__Young
Subject: SongRequest

A Good Night's Sleep and a Cab Far...
From: cosmicprincescthulTraceback (most recent call last):
  File "/home/redditbot/SteamieBot/steamiebot.py", line 246, in tryPost
    postSteamie(configFile)
  File "/home/redditbot/SteamieBot/steamiebot.py", line 234, in postSteamie
    print post[1]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xec' in position 3024: ordinal not in range(128)
Traceback (most recent call last):                                                                                                              
  File "/home/redditbot/SteamieBot/steamiebot.py", line 246, in tryPost
    postSteamie(configFile)
  File "/home/redditbot/SteamieBot/steamiebot.py", line 234, in postSteamie
    print post[1]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xec' in position 3024: ordinal not in range(128)
hu
Subject: SongRequest

https://www.youtube.com/watc...
The Steamie - Monday 18 January 2016


Failed to make daily post. Waiting 15 minutes to retry. Error: 
Attempting to post 'The Steamie'
From: 88ytre
Subject: SongRequest

https://www.youtube.com/watch?v=SO-Mk-Ysqbs
From: 88ytre
Subject: SongRequest

https://www.youtube.com/watch?v=KnIgXtE4K5U
From: cosmicprincescthulhu
Subject: SongRequest

https://www.youtube.com/watc...
From: Ghost_Hands83
Subject: SongRequest                                                                                                                            

https://youtu.be/LZyqaM1hgCQ
From: Forever__Young
Subject: SongRequest

A Good Night's Sleep and a Cab Far...
From: cosmicprincescthulhu
Subject: SongRequest

https://www.youtube.com/watc...
The Steamie - Monday 18 January 2016


Failed to make daily post. Waiting 15 minutes to retry. Error:

**Comment by timlardner** [comment] 2016-01-18 09:00
Not sure why it's failing when run via cron but seems ok when run manually.

**Comment by maaarghk** [comment] 2016-01-18 09:39
There's a unicode character in the post - one of the gig listings: "Così fan tutte", and there was some french in yesterday's too. The user won't have the right character set - set the environment by changing the cron task to `cd /home/redditbot/SteamieBot; PYTHONIOENCODING=utf8 python run_steamie.py"

**Comment by timlardner** [comment] 2016-01-18 10:45
Change made.

**Comment by maaarghk** [comment] 2016-01-19 12:28
Not that then? Might need to put the PYTHONIOENCODING at the top of the cron tab or failing that in a steamiebot.sh file to run instead.

**Comment by timlardner** [comment] 2016-01-19 12:51
Made that change too. Failing that, we can just disable the printing of the post to the console - it should probably be going to a log file anyway.

**Comment by timlardner** [comment] 2016-01-20 07:51
Posted correctly today even though there are non-ascii characters in the post. Seems the problem is fixed.

**Comment by maaarghk** [comment] 2016-01-29 09:12
I'm going to close this and create new issues for WOTD / Day in History

**Closed by maaarghk** 2016-01-29 09:12 UTC
